import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const teste = "teste"
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <section className={styles.section_1}>
                <div className={styles.banner_home_1}>
                    <h1 className={styles.banner_home_1_title}>você está pronto para voar?</h1>
                    <span className={styles.banner_home_1_subtitle}>
                    “Desistir nunca foi uma opção pra mim, dentro desse contexto minha meta de vida se tornou mostrar para todas as pessoas que eu puder a força que ela tem. O Pole Dance me deu essa oportunidade.”
                    </span>
                    <p>{teste}</p>
                </div>
            </section>
            <section>
                <h2>Images</h2>
            </section>
            <section>
                <h3>Section 3</h3>
            </section>
            <section>
                <h4>Section 4</h4>
            </section>

            <footer className={styles.footer}>
                <a
                    href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                    target="_blank"
                    rel="noopener noreferrer"
                >
                    Powered by{" "}
                    <span className={styles.logo}>
                        <Image
                            src="/vercel.svg"
                            alt="Vercel Logo"
                            width={72}
                            height={16}
                        />
                    </span>
                </a>
            </footer>
        </div>
    );
}
